---
name: "rails3"
runtimes:
  - ruby18.current:
      default: true
      environment:
       rails_env: "production"
       bundle_gemfile:
       rack_env: "production"
  - ruby19.current:
      environment:
       rails_env: "production"
       bundle_gemfile:
       rack_env: "production"
app_servers:
  - "thin":
      description: "Thin"
      executable: false
      default: true
detection:
  - "config/application.rb": true
  - "config/environment.rb": true
staged_services:
  - "name": "mysql"
    "version": "*"
  - "name": "postgresql"
    "version": "*"

# vim: filetype=yaml
