source "http://rubygems.org"
gem "rake"
gem "sinatra"
gem "json"
group :test do
  gem "rspec"
end
gem "redis", :group => :development
gem "uglifier", :groups => [:assets, :test]
gem "rubyzip", :group => :development
group :assets do
  gem "thor"
end
gem "vcap_common", '~> 2.0.0', :git => 'git://github.com/cloudfoundry/vcap-common.git', :ref => '5334b662'
